apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-router
  labels:
    app: mqtt-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-router
  template:
    metadata:
      labels:
        app: mqtt-router
    spec:
      containers:
      - name: mqtt-router
        image: docker.io/sky010/mqtt-router:latest
        ports:
        - containerPort: 8080
        env:
        - name: broker
          value: "tcp://10.0.2.15:1883"
        - name: gw-username
          value: "admin"
        - name: gw-password
          value: "yInlcVgmSbjf" # Gateway password obtained by running sudo kubectl get secret -n openfaas basic-auth -o jsonpath="{.data.basic-auth-password}" | base64 --decode
        - name: gw-flag
          value: "http://gateway.openfaas:8080"
        - name: url-monitoring
          value: "http://monitoring-service.default.svc.cluster.local:8080"