apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: openfaas
  name: router
  labels:
    app: proxy-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-router
  template:
    metadata:
      labels:
        app: proxy-router
    spec:
      containers:
      - name: proxy-router
        image: docker.io/sky010/proxy-router:latest
        ports:
        - containerPort: 8080
        env:
        - name: client-id
          value: "routerVPS"
        - name: broker
          value: "tcp://10.133.33.52:1883"
        - name: url-monitoring
          value: "http://100.104.175.11:30080"
        - name: url-invoker
          value: "http://100.104.175.11:30081"
        - name: url-other-invoker
          value: "http://100.118.252.122:30081"