apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoker
  namespace: openfaas
  labels:
    app: proxy-invoker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-invoker
  template:
    metadata:
      labels:
        app: proxy-invoker
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - nikos0
      tolerations:
      - key: "key"
        operator: "Equal"
        value: "value"
        effect: "NoExecute"
      containers:
      - name: invoker
        image: docker.io/sky010/proxy-invoker:armv7
        ports:
        - containerPort: 8080
        env:
        - name: gw-url
          value: "http://gateway.openfaas:8080"
        - name: gw-username
          value: "admin"
        - name: gw-password
          valueFrom:
            secretKeyRef:
              name: basic-auth
              key: basic-auth-password
        - name: port
          value: "8080"

---
apiVersion: v1
kind: Service
metadata:
  name: invoker-service
  namespace: openfaas
spec:
  selector:
    app: proxy-invoker
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30081
  type: NodePort